//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTap3.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class EmployeeInformation
    {
        public int Id { get; set; }
        public string empID { get; set; }
        public string empName { get; set; }
        public DateTime empDateOfBirth { get; set; }
        public string empEmail { get; set; }
        public string empPassword { get; set; }
        public string empDivision { get; set; }
        public string empImg { get; set; }
        public HttpPostedFileBase imgFile { get; set; }

    }
}
