//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTap3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    
    public partial class EmployeeInformation
    {
        public int Id { get; set; }
        [DisplayName("Mã nhân viên: ")]
        public string empID { get; set; }
        [DisplayName("Họ tên: ")]

        public string empName { get; set; }
        [DisplayName("Ngày sinh: ")]

        public DateTime empDateOfBirth { get; set; }
        [DisplayName("Email: ")]

        public string empEmail { get; set; }
        [DisplayName("Mật khẩu: ")]

        public string empPassword { get; set; }
        [DisplayName("Đơn vị: ")]

        public string empDivision { get; set; }
        [DisplayName("Chọn ảnh:  ")]

        public string empImg { get; set; }
        public HttpPostedFileBase imgFile { get; set; }

    }
}
